version: '2'

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER=geek_beacon
      - POSTGRES_PASSWORD=geek_beacon
      - USE_DOCKER=yes
      - DISQUS_API_KEY=woot
    ports:
      - "8000:8000"
    command: /start.sh
  postgres:
    image: geekbeacon/postgres
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    environment:
      - POSTGRES_USER=geek_beacon
      - POSTGRES_PASSWORD=geek_beacon
    volumes:
      - ./volumes/postgres_data_local:/var/lib/postgresql/data
      - ./volumes/postgres_backup_local:/backups
    ports:
      - "5432:5432"
